name: Test building the standard

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended xsltproc
      
    - name: Build the document
      run: make biblio forcetex
      
    - name: Check the output
      run: |
        test -f ConeSearch.pdf
        test -f ConeSearch.bbl
